sources:
  viirs_base_url: "https://edcftp.cr.usgs.gov/project/FEWSNET/spervez/Togofiles/SouthSudan/UofReading/Geotiffs/"
  modis_base_url: "https://data.earthobservation.vam.wfp.org/public-share/sudd_wetland_monitoring/modis_flood_masks/ssdmask"
  rainfall_url: "https://gws-access.jasmin.ac.uk/public/tamsat/INFLOW/rainfall/rfe_time-series/combined/rfe_19830101-present_Lake-Victoria.csv"
  teleconnections:
    oni: "https://www.cpc.ncep.noaa.gov/data/indices/oni.ascii.txt"
    sst: "https://www.cpc.ncep.noaa.gov/data/indices/sstoi.indices"
    soi: "https://www.cpc.ncep.noaa.gov/data/indices/soi"
    mjo: "https://www.cpc.ncep.noaa.gov/products/precip/CWlink/daily_mjo_index/proj_norm_order.ascii"
    dmi: "https://www.cpc.ncep.noaa.gov/products/international/ocean_monitoring/indian/IODMI/mnth.ersstv5.clim19912020.dmi_current.txt"

paths:
  downloads:
    inundation_modis: "data/downloads/inundation_masks_modis"
    inundation_viirs: "data/downloads/inundation_masks_viirs"
    teleconnections: "data/downloads/teleconnections"
    tamsat: "data/downloads/tamsat"
  historic:
    inundation_h5: "data/historic/inundation.h5"
    inundation_temporal_unscaled: "data/historic/inundation_temporal_unscaled.csv"
    inundation_temporal_scaled: "data/historic/inundation_temporal_scaled.csv"
    viirs_h5: "data/historic/viirs_inundation.h5"
    viirs_temporal_unscaled: "data/historic/viirs_inundation_temporal_unscaled.csv"
    viirs_temporal_scaled: "data/historic/viirs_inundation_temporal_scaled.csv"
    teleconnections: "data/historic/teleconnections.csv"
    rainfall: "data/historic/rainfall.csv"
  maps:
    catchments: "data/maps/inflow_catchments/INFLOW_all_cmts.shp"
    admin0: "data/maps/admin_boundaries/ssd_admbnda_adm0_imwg_nbs_20230829.shp"
    admin1: "data/maps/admin_boundaries/ssd_admbnda_adm1_imwg_nbs_20230829.shp"
    abyei: "data/maps/abyei_region/ssd_admbnda_abyei_imwg_nbs_20180401.shp"

reference_grid:
  mask_regions:
    crs: "EPSG:6933"
    transform: [1000.0, 0.0, 2260000.0, 0.0, -1000.0, 1558000.0]
    shape: [1125, 1204]
    bounds: [2260000.0, 433000.0, 3464000.0, 1558000.0]

runtime:
  study_start_date: "2002-07-01"
  teleconnections:
    min_date: "2002-07-01"
